"""Increase password_hash to 255 chars for scrypt

Revision ID: 12513a45815e
Revises: 0abf9dbc680d
Create Date: 2025-12-07 18:20:35.198679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12513a45815e'
down_revision = '0abf9dbc680d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)

    # ### end Alembic commands ###
