"""add user_id to category, unit, location

Revision ID: 1e79098e537b
Revises: 5a980f64f209
Create Date: 2025-12-17 07:24:36.995165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e79098e537b'
down_revision = '5a980f64f209'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key( "fk_category_user_id_user", 'user', ['user_id'], ['id'])

    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key("fk_location_user_id_user", 'user', ['user_id'], ['id'])

    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key( "fk_units_user_id_user", 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.drop_constraint("fk_units_user_id_user", type_='foreignkey')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.drop_constraint("fk_location_user_id_user", type_='foreignkey')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_constraint("fk_category_user_id_user", type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
