"""Set ondelete CASCADE on consumption_log.grocery_iten_id

Revision ID: 32d5e4fff965
Revises: 404c163ca3db
Create Date: 2025-12-12 23:07:14.234408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32d5e4fff965'
down_revision = '404c163ca3db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consumption_log', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('consumption_log_grocery_item_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'grocery_item', ['grocery_item_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consumption_log', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('consumption_log_grocery_item_id_fkey'), 'grocery_item', ['grocery_item_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###
