"""Add profile model

Revision ID: 36985250c66e
Revises: a13d1c4830fb
Create Date: 2025-12-15 15:10:24.266933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36985250c66e'
down_revision = 'a13d1c4830fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=True),
    sa.Column('phone_number', sa.String(length=30), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('avatar_url', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profile')
    # ### end Alembic commands ###
