"""Set ondelete SET NULL on food_wasted.grocery_item_id

Revision ID: 404c163ca3db
Revises: 5abbf095b5bf
Create Date: 2025-12-12 22:40:44.057843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '404c163ca3db'
down_revision = '5abbf095b5bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('food_wasted', schema=None) as batch_op:
        batch_op.alter_column('grocery_item_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('food_wasted_grocery_item_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'grocery_item', ['grocery_item_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('food_wasted', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('food_wasted_grocery_item_id_fkey'), 'grocery_item', ['grocery_item_id'], ['id'])
        batch_op.alter_column('grocery_item_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
