"""modified the WastedFood model

Revision ID: 5015c3d22fd9
Revises: daf28cb555d8
Create Date: 2025-12-14 14:23:51.826623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5015c3d22fd9'
down_revision = 'daf28cb555d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consumption_log', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('consumption_log_grocery_item_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'grocery_item', ['grocery_item_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('food_wasted', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_name', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('quantity', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('expiry_date', sa.Date(), nullable=True))
        batch_op.drop_constraint(batch_op.f('food_wasted_grocery_item_id_fkey'), type_='foreignkey')
        batch_op.drop_column('grocery_item_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('food_wasted', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grocery_item_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('food_wasted_grocery_item_id_fkey'), 'grocery_item', ['grocery_item_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_column('expiry_date')
        batch_op.drop_column('quantity')
        batch_op.drop_column('item_name')

    with op.batch_alter_table('consumption_log', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('consumption_log_grocery_item_id_fkey'), 'grocery_item', ['grocery_item_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
