"""Rename user table to users

Revision ID: 5227240c405b
Revises: 36985250c66e
Create Date: 2025-12-15 19:12:05.558664

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5227240c405b'
down_revision = '36985250c66e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('users',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('username', sa.String(length=120), nullable=False),
    # sa.Column('email', sa.String(length=120), nullable=False),
    # sa.Column('password_hash', sa.String(length=255), nullable=False),
    # sa.Column('role', sa.String(length=50), nullable=True),
    # sa.Column('created_at', sa.DateTime(), nullable=True),
    # sa.PrimaryKeyConstraint('id'),
    # sa.UniqueConstraint('email'),
    # sa.UniqueConstraint('username')
    # )
    # op.drop_table('user')
    # with op.batch_alter_table('consumption_log', schema=None) as batch_op:
    #     batch_op.drop_constraint(batch_op.f('consumption_log_user_id_fkey'), type_='foreignkey')
    #     batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    # with op.batch_alter_table('food_wasted', schema=None) as batch_op:
    #     batch_op.drop_constraint(batch_op.f('food_wasted_user_id_fkey'), type_='foreignkey')
    #     batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    # with op.batch_alter_table('grocery_item', schema=None) as batch_op:
    #     batch_op.drop_constraint(batch_op.f('grocery_item_user_id_fkey'), type_='foreignkey')
    #     batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    # with op.batch_alter_table('profile', schema=None) as batch_op:
    #     batch_op.drop_constraint(batch_op.f('profile_user_id_fkey'), type_='foreignkey')
    #     batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    # with op.batch_alter_table('shopping_list_item', schema=None) as batch_op:
    #     batch_op.drop_constraint(batch_op.f('shopping_list_item_user_id_fkey'), type_='foreignkey')
    #     batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('shopping_list_item', schema=None) as batch_op:
    #     batch_op.drop_constraint(None, type_='foreignkey')
    #     batch_op.create_foreign_key(batch_op.f('shopping_list_item_user_id_fkey'), 'user', ['user_id'], ['id'])

    # with op.batch_alter_table('profile', schema=None) as batch_op:
    #     batch_op.drop_constraint(None, type_='foreignkey')
    #     batch_op.create_foreign_key(batch_op.f('profile_user_id_fkey'), 'user', ['user_id'], ['id'])

    # with op.batch_alter_table('grocery_item', schema=None) as batch_op:
    #     batch_op.drop_constraint(None, type_='foreignkey')
    #     batch_op.create_foreign_key(batch_op.f('grocery_item_user_id_fkey'), 'user', ['user_id'], ['id'])

    # with op.batch_alter_table('food_wasted', schema=None) as batch_op:
    #     batch_op.drop_constraint(None, type_='foreignkey')
    #     batch_op.create_foreign_key(batch_op.f('food_wasted_user_id_fkey'), 'user', ['user_id'], ['id'])

    # with op.batch_alter_table('consumption_log', schema=None) as batch_op:
    #     batch_op.drop_constraint(None, type_='foreignkey')
    #     batch_op.create_foreign_key(batch_op.f('consumption_log_user_id_fkey'), 'user', ['user_id'], ['id'])
    pass

    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('user_pkey')),
    sa.UniqueConstraint('email', name=op.f('user_email_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('username', name=op.f('user_username_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
   
