"""modified the consumptionlogs  model

Revision ID: 52f3477dcbaa
Revises: 5015c3d22fd9
Create Date: 2025-12-14 14:42:24.033281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52f3477dcbaa'
down_revision = '5015c3d22fd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consumption_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_name', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('item_category', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consumption_log', schema=None) as batch_op:
        batch_op.drop_column('item_category')
        batch_op.drop_column('item_name')

    # ### end Alembic commands ###
