"""Add ShoppingListItem with purchased flag

Revision ID: 9b2b32f11920
Revises: 203565446950
Create Date: 2025-12-10 14:12:20.422206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b2b32f11920'
down_revision = '203565446950'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shopping_list_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grocery_item_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'grocery_item', ['grocery_item_id'], ['id'])
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shopping_list_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('grocery_item_id')

    # ### end Alembic commands ###
