"""Set ondelete CASCADE on consumption_log.grocery_iten_id

Revision ID: daf28cb555d8
Revises: 32d5e4fff965
Create Date: 2025-12-12 23:07:43.384857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'daf28cb555d8'
down_revision = '32d5e4fff965'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consumption_log', schema=None) as batch_op:
        batch_op.alter_column('grocery_item_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consumption_log', schema=None) as batch_op:
        batch_op.alter_column('grocery_item_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
