"""Added food wasted model

Revision ID: dfa0600233c8
Revises: 18b2aa7712ab
Create Date: 2025-12-12 17:06:12.189215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfa0600233c8'
down_revision = '18b2aa7712ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('food_wasted',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grocery_item_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['grocery_item_id'], ['grocery_item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('food_wasted')
    # ### end Alembic commands ###
